sudo: false
language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=master git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - git clone --depth=50 --branch=master https://github.com/digital-canvas/zend-framework.git ../zendlib
  - cd ../aimeos-core
  - mv ../ai-zend ext/ai-zend
  - composer install || sleep 60 && composer install

script: vendor/bin/phing -Ddir=ext/ai-zend -Dzenddir=`pwd`/../zendlib/library coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-zend/.coveralls.yml
