language: php
php:
  - "hhvm"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - git clone --depth=50 --branch=master git://github.com/nsendetzky/arcavias-core.git ../arcavias-core
  - git clone --depth=50 --branch=master https://github.com/digital-canvas/zend-framework.git ../zendlib
  - cd ../arcavias-core
  - mv ../ai-zend ext/ai-zend
  - composer install || sleep 60 && composer install
script: "vendor/bin/phing -Ddir=ext/ai-zend -Dzenddir=`pwd`/../zendlib/library testext && vendor/bin/phing -Ddir=ext/ai-zend checkext"
